### ISSUE TITLE
Scalatex-site 0.3.5 doesn't work with scalatags 0.5.5

### ISSUE THREAD

**Issue by ptxmac** [lihaoyi/Scalatex#27]
Some change between scalatag 0.5.4 and 0.5.5 broke the css part of scalatex-site

```
java.lang.NoSuchMethodError: scalatags.stylesheet.StyleSheet$cls$.apply(Lscala/collection/Seq;)Lscalatags/stylesheet/Cls;
	at scalatex.site.Styles$class.headerLink(Styles.scala:12)
	at scalatex.site.Styles$$anon$1.headerLink$lzycompute(Styles.scala:6)
	at scalatex.site.Styles$$anon$1.headerLink(Styles.scala:6)
	at scalatex.site.Section$class.headingAnchor(Section.scala:108)
	at scalatex.Frontpage$sect$2$.headingAnchor(Frontpage.scala:3)
	at scalatex.site.Section$$anonfun$apply$2.apply(Section.scala:127)
	at scalatex.site.Section$$anonfun$apply$2.apply(Section.scala:122)
	at scalatex.site.Section$Proxy.apply(Section.scala:11)
	at scalatex.Frontpage$.apply(Frontpage.scala:5)
	at blog.Site$.index(Site.scala:39)
	at blog.Site$.generate(Site.scala:53)
	at blog.Main$.main(Main.scala:60)
	at blog.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by lihaoyi** [comment]
0.3.6 should fix this
